SETTINGS = "🛠 Налаштування"
START_TRAINING = "🏅 Почати тренування"
CONFIGURE_NOTIFICATIONS = "🔔 Налаштування сповіщень"
GO_BACK = "◀️ Назад"
CHANGE_NOTIFICATION_TIME = "🕒 Змінити час сповіщень"
TURN_ON_OFF_NOTIFICATIONS = "📢 Увімкнути/Вимкнути"
