"""update notifications models

Revision ID: 1ca58141862d
Revises: 44f4540f66d3
Create Date: 2025-04-17 12:49:06.128613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca58141862d'
down_revision: Union[str, None] = '44f4540f66d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_notifications', sa.Column('notification_time', sa.Time(), nullable=False))
    op.add_column('custom_notifications', sa.Column('last_execution_datetime', sa.DateTime(), nullable=True))
    op.add_column('custom_notifications', sa.Column('next_execution_datetime', sa.DateTime(), nullable=True))
    op.add_column('custom_notifications', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    op.drop_constraint('custom_notifications_notification_preference_id_fkey', 'custom_notifications', type_='foreignkey')
    op.drop_column('custom_notifications', 'notification_preference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_notifications', sa.Column('notification_preference_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('custom_notifications_notification_preference_id_fkey', 'custom_notifications', 'notification_preferences', ['notification_preference_id'], ['id'])
    op.drop_column('custom_notifications', 'notification_sent')
    op.drop_column('custom_notifications', 'next_execution_datetime')
    op.drop_column('custom_notifications', 'last_execution_datetime')
    op.drop_column('custom_notifications', 'notification_time')
    # ### end Alembic commands ###
