"""Add weekly_stats_counter and last_stats_sent_date to User model

Revision ID: 1dad97c27ce0
Revises: e2dceb40a8d7
Create Date: 2025-04-20 22:08:55.295736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dad97c27ce0'
down_revision: Union[str, None] = 'e2dceb40a8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('weekly_stats_counter', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_stats_sent_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_stats_sent_date')
    op.drop_column('users', 'weekly_stats_counter')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
