"""Update notifications and morning quiz

Revision ID: 4038a43a146e
Revises: c0cff252e0fc
Create Date: 2025-01-20 14:20:26.543495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4038a43a146e"
down_revision: Union[str, None] = "c0cff252e0fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_preferences",
        sa.Column("notification_message", sa.String(), nullable=True),
    )
    op.add_column(
        "user_morning_quiz",
        sa.Column(
            "is_going_to_have_training",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    op.add_column(
        "user_morning_quiz",
        sa.Column("expected_training_datetime", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_morning_quiz", "expected_training_datetime")
    op.drop_column("user_morning_quiz", "is_going_to_have_training")
    op.drop_column("notification_preferences", "notification_message")
    # ### end Alembic commands ###
