"""create custom notifications

Revision ID: 44f4540f66d3
Revises: 8f2f1cbe8e42
Create Date: 2025-04-17 01:38:46.996021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f4540f66d3'
down_revision: Union[str, None] = '8f2f1cbe8e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_preference_id', sa.Integer(), nullable=False),
    sa.Column('notification_name', sa.String(), nullable=False),
    sa.Column('notification_message', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_preference_id'], ['notification_preferences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_notifications_id'), 'custom_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_notifications_id'), table_name='custom_notifications')
    op.drop_table('custom_notifications')
    # ### end Alembic commands ###
