"""Added is_active to noti

Revision ID: 64b1805f6da0
Revises: 98c6ef39fde0
Create Date: 2024-12-31 13:09:12.610728

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64b1805f6da0"
down_revision: Union[str, None] = "98c6ef39fde0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_preferences", sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification_preferences", "is_active")
    # ### end Alembic commands ###
