"""Update notification model

Revision ID: 7fd5663f8a52
Revises: 8a67a49e213d
Create Date: 2025-01-20 21:03:02.306621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd5663f8a52'
down_revision: Union[str, None] = '8a67a49e213d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'notification_sent')
    # ### end Alembic commands ###
