"""Add notification preferences connection to user

Revision ID: 98c6ef39fde0
Revises: f1ed768fe750
Create Date: 2024-12-24 16:53:37.011585

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "98c6ef39fde0"
down_revision: Union[str, None] = "f1ed768fe750"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
