"""Update user_sleeping_hours to be time , not integer

Revision ID: c0cff252e0fc
Revises: e3f4e14d548e
Create Date: 2025-01-17 19:08:48.845136

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0cff252e0fc"
down_revision: Union[str, None] = "e3f4e14d548e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
            ALTER TABLE user_morning_quiz 
            ALTER COLUMN user_sleeping_hours 
            TYPE TIME WITHOUT TIME ZONE 
            USING to_char(user_sleeping_hours, '00:00')::TIME;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
           ALTER TABLE user_morning_quiz 
           ALTER COLUMN user_sleeping_hours 
           TYPE INTEGER 
           USING EXTRACT(HOUR FROM user_sleeping_hours) * 100 + EXTRACT(MINUTE FROM user_sleeping_hours);
       """
    )
