"""update notifications models_2

Revision ID: e2dceb40a8d7
Revises: 1ca58141862d
Create Date: 2025-04-17 14:29:28.287193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2dceb40a8d7'
down_revision: Union[str, None] = '1ca58141862d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_notifications', sa.Column('periodicity_type', sa.String(), nullable=False))
    op.add_column('custom_notifications', sa.Column('specific_days', sa.String(), nullable=True))
    op.alter_column('custom_notifications', 'next_execution_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('custom_notifications', 'last_execution_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('custom_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('custom_notifications', 'last_execution_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('custom_notifications', 'next_execution_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('custom_notifications', 'specific_days')
    op.drop_column('custom_notifications', 'periodicity_type')
    # ### end Alembic commands ###
