"""Fix notifications

Revision ID: e3f4e14d548e
Revises: bfbc1339f760
Create Date: 2025-01-10 18:52:48.019279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3f4e14d548e"
down_revision: Union[str, None] = "bfbc1339f760"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_preferences",
        sa.Column("notification_time", sa.Time(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification_preferences", "notification_time")
    # ### end Alembic commands ###
